namespace UnityEngine.Rendering.HighDefinition
{
	[GenerateHLSL(PackingRules.Exact, true, false, false, 1, false, false, false, -1, ".\\Library\\PackageCache\\com.unity.render-pipelines.high-definition@14.0.8\\Runtime\\Debug\\DebugDisplay.cs")]
	public enum FullScreenDebugMode
	{
		None = 0,
		MinLightingFullScreenDebug = 1,
		ScreenSpaceAmbientOcclusion = 2,
		ScreenSpaceReflections = 3,
		TransparentScreenSpaceReflections = 4,
		ScreenSpaceReflectionsPrev = 5,
		ScreenSpaceReflectionsAccum = 6,
		ScreenSpaceReflectionSpeedRejection = 7,
		ContactShadows = 8,
		ContactShadowsFade = 9,
		ScreenSpaceShadows = 10,
		PreRefractionColorPyramid = 11,
		DepthPyramid = 12,
		FinalColorPyramid = 13,
		LightCluster = 14,
		ScreenSpaceGlobalIllumination = 15,
		RecursiveRayTracing = 16,
		RayTracedSubSurface = 17,
		VolumetricClouds = 18,
		VolumetricCloudsShadow = 19,
		RayTracingAccelerationStructure = 20,
		MaxLightingFullScreenDebug = 21,
		MinRenderingFullScreenDebug = 22,
		MotionVectors = 23,
		WorldSpacePosition = 24,
		NanTracker = 25,
		ColorLog = 26,
		DepthOfFieldCoc = 27,
		TransparencyOverdraw = 28,
		QuadOverdraw = 29,
		LocalVolumetricFogOverdraw = 30,
		VertexDensity = 31,
		RequestedVirtualTextureTiles = 32,
		LensFlareDataDriven = 33,
		MaxRenderingFullScreenDebug = 34,
		MinMaterialFullScreenDebug = 35,
		ValidateDiffuseColor = 36,
		ValidateSpecularColor = 37,
		MaxMaterialFullScreenDebug = 38
	}
}
