using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Security.Permissions;

[assembly: InternalsVisibleTo("Unity.RenderPipelines.HighDefinition.Editor")]
[assembly: InternalsVisibleTo("Unity.RenderPipelines.HighDefinition.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.RenderPipelines.HighDefinition.Runtime.Tests")]
[assembly: InternalsVisibleTo("HDRP_TestRunner")]
[assembly: InternalsVisibleTo("Unity.TextMeshPro.Editor")]
[assembly: InternalsVisibleTo("Unity.Industrial.Materials.AVRD.Runtime")]
[assembly: InternalsVisibleTo("Unity.Industrial.Materials.AVRD.Editor")]
[assembly: InternalsVisibleTo("Unity.RenderPipelines.HighDefinition-Tests.Runtime")]
[assembly: InternalsVisibleTo("Unity.RenderPipelines.HighDefinition-Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.GraphicTests.Performance.HDRP.Runtime")]
[assembly: InternalsVisibleTo("Unity.GraphicTests.Performance.HDRP.Editor")]
[assembly: InternalsVisibleTo("TestRuntime")]
[assembly: InternalsVisibleTo("Unity.SensorSDK.Runtime")]
[assembly: InternalsVisibleTo("Unity.SensorSDK.Editor")]
[assembly: AssemblyVersion("0.0.0.0")]
